/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as MerchantsIndexRouteImport } from './routes/merchants/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as OrderLookupRouteImport } from './routes/order/lookup'
import { Route as MerchantsMerchantIdRouteImport } from './routes/merchants/$merchantId'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as HelpContactRouteImport } from './routes/help/contact'
import { Route as ContentSlugRouteImport } from './routes/content/$slug'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiTrackEventRouteImport } from './routes/api/track-event'
import { Route as ApiGuestOrderLookupRouteImport } from './routes/api/guest-order-lookup'
import { Route as ApiExchangeRatesRouteImport } from './routes/api/exchange-rates'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiMerchantsIndexRouteImport } from './routes/api/merchants/index'
import { Route as ApiCartIndexRouteImport } from './routes/api/cart/index'
import { Route as AdminSupportIndexRouteImport } from './routes/admin/support/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as OrderOrderIdConfirmationRouteImport } from './routes/order/$orderId/confirmation'
import { Route as ApiProductsProductIdRouteImport } from './routes/api/products/$productId'
import { Route as ApiOrdersOrderIdRouteImport } from './routes/api/orders/$orderId'
import { Route as ApiMerchantsMerchantIdRouteImport } from './routes/api/merchants/$merchantId'
import { Route as ApiCartUserRouteImport } from './routes/api/cart/user'
import { Route as ApiCartMergeRouteImport } from './routes/api/cart/merge'
import { Route as ApiCartClaimRouteImport } from './routes/api/cart/claim'
import { Route as AdminSupportInquiryIdRouteImport } from './routes/admin/support/$inquiryId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as ApiCartCartIdIndexRouteImport } from './routes/api/cart/$cartId/index'
import { Route as ApiMerchantsMerchantIdProductsRouteImport } from './routes/api/merchants/$merchantId/products'
import { Route as ApiCollectionsCollectionIdProductsRouteImport } from './routes/api/collections/$collectionId/products'
import { Route as ApiCartOffersOfferIdRouteImport } from './routes/api/cart/offers/$offerId'
import { Route as ApiCartCartIdSubmitRouteImport } from './routes/api/cart/$cartId/submit'
import { Route as ApiCartCartIdShipping_addressRouteImport } from './routes/api/cart/$cartId/shipping_address'
import { Route as ApiCartCartIdShippingRouteImport } from './routes/api/cart/$cartId/shipping'
import { Route as ApiCartCartIdPriceRouteImport } from './routes/api/cart/$cartId/price'
import { Route as ApiCartCartIdPaymentIntentRouteImport } from './routes/api/cart/$cartId/payment-intent'
import { Route as ApiCartCartIdCustomerRouteImport } from './routes/api/cart/$cartId/customer'
import { Route as ApiCartCartIdBilling_addressRouteImport } from './routes/api/cart/$cartId/billing_address'
import { Route as ApiCartCartIdSkusIndexRouteImport } from './routes/api/cart/$cartId/skus/index'
import { Route as ApiCartCartIdSkusSkuIdRouteImport } from './routes/api/cart/$cartId/skus/$skuId'
import { Route as ApiCartCartIdShippingAvailableRouteImport } from './routes/api/cart/$cartId/shipping/available'
import { Route as ApiCartCartIdOrdersOrderIdRouteImport } from './routes/api/cart/$cartId/orders/$orderId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsIndexRoute = MerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderLookupRoute = OrderLookupRouteImport.update({
  id: '/order/lookup',
  path: '/order/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsMerchantIdRoute = MerchantsMerchantIdRouteImport.update({
  id: '/merchants/$merchantId',
  path: '/merchants/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpContactRoute = HelpContactRouteImport.update({
  id: '/help/contact',
  path: '/help/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSlugRoute = ContentSlugRouteImport.update({
  id: '/content/$slug',
  path: '/content/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackEventRoute = ApiTrackEventRouteImport.update({
  id: '/api/track-event',
  path: '/api/track-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestOrderLookupRoute = ApiGuestOrderLookupRouteImport.update({
  id: '/api/guest-order-lookup',
  path: '/api/guest-order-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRatesRoute = ApiExchangeRatesRouteImport.update({
  id: '/api/exchange-rates',
  path: '/api/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMerchantsIndexRoute = ApiMerchantsIndexRouteImport.update({
  id: '/api/merchants/',
  path: '/api/merchants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartIndexRoute = ApiCartIndexRouteImport.update({
  id: '/api/cart/',
  path: '/api/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/admin/support/',
  path: '/admin/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const OrderOrderIdConfirmationRoute =
  OrderOrderIdConfirmationRouteImport.update({
    id: '/order/$orderId/confirmation',
    path: '/order/$orderId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsProductIdRoute = ApiProductsProductIdRouteImport.update({
  id: '/api/products/$productId',
  path: '/api/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdRoute = ApiOrdersOrderIdRouteImport.update({
  id: '/api/orders/$orderId',
  path: '/api/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMerchantsMerchantIdRoute = ApiMerchantsMerchantIdRouteImport.update({
  id: '/api/merchants/$merchantId',
  path: '/api/merchants/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartUserRoute = ApiCartUserRouteImport.update({
  id: '/api/cart/user',
  path: '/api/cart/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartMergeRoute = ApiCartMergeRouteImport.update({
  id: '/api/cart/merge',
  path: '/api/cart/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartClaimRoute = ApiCartClaimRouteImport.update({
  id: '/api/cart/claim',
  path: '/api/cart/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportInquiryIdRoute = AdminSupportInquiryIdRouteImport.update({
  id: '/admin/support/$inquiryId',
  path: '/admin/support/$inquiryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ApiCartCartIdIndexRoute = ApiCartCartIdIndexRouteImport.update({
  id: '/api/cart/$cartId/',
  path: '/api/cart/$cartId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMerchantsMerchantIdProductsRoute =
  ApiMerchantsMerchantIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ApiMerchantsMerchantIdRoute,
  } as any)
const ApiCollectionsCollectionIdProductsRoute =
  ApiCollectionsCollectionIdProductsRouteImport.update({
    id: '/api/collections/$collectionId/products',
    path: '/api/collections/$collectionId/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCartOffersOfferIdRoute = ApiCartOffersOfferIdRouteImport.update({
  id: '/api/cart/offers/$offerId',
  path: '/api/cart/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdSubmitRoute = ApiCartCartIdSubmitRouteImport.update({
  id: '/api/cart/$cartId/submit',
  path: '/api/cart/$cartId/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdShipping_addressRoute =
  ApiCartCartIdShipping_addressRouteImport.update({
    id: '/api/cart/$cartId/shipping_address',
    path: '/api/cart/$cartId/shipping_address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCartCartIdShippingRoute = ApiCartCartIdShippingRouteImport.update({
  id: '/api/cart/$cartId/shipping',
  path: '/api/cart/$cartId/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdPriceRoute = ApiCartCartIdPriceRouteImport.update({
  id: '/api/cart/$cartId/price',
  path: '/api/cart/$cartId/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdPaymentIntentRoute =
  ApiCartCartIdPaymentIntentRouteImport.update({
    id: '/api/cart/$cartId/payment-intent',
    path: '/api/cart/$cartId/payment-intent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCartCartIdCustomerRoute = ApiCartCartIdCustomerRouteImport.update({
  id: '/api/cart/$cartId/customer',
  path: '/api/cart/$cartId/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdBilling_addressRoute =
  ApiCartCartIdBilling_addressRouteImport.update({
    id: '/api/cart/$cartId/billing_address',
    path: '/api/cart/$cartId/billing_address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCartCartIdSkusIndexRoute = ApiCartCartIdSkusIndexRouteImport.update({
  id: '/api/cart/$cartId/skus/',
  path: '/api/cart/$cartId/skus/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdSkusSkuIdRoute = ApiCartCartIdSkusSkuIdRouteImport.update({
  id: '/api/cart/$cartId/skus/$skuId',
  path: '/api/cart/$cartId/skus/$skuId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartCartIdShippingAvailableRoute =
  ApiCartCartIdShippingAvailableRouteImport.update({
    id: '/available',
    path: '/available',
    getParentRoute: () => ApiCartCartIdShippingRoute,
  } as any)
const ApiCartCartIdOrdersOrderIdRoute =
  ApiCartCartIdOrdersOrderIdRouteImport.update({
    id: '/api/cart/$cartId/orders/$orderId',
    path: '/api/cart/$cartId/orders/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/health': typeof AdminHealthRoute
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/guest-order-lookup': typeof ApiGuestOrderLookupRoute
  '/api/track-event': typeof ApiTrackEventRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/content/$slug': typeof ContentSlugRoute
  '/help/contact': typeof HelpContactRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/order/lookup': typeof OrderLookupRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/content/': typeof ContentIndexRoute
  '/help/': typeof HelpIndexRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/support/$inquiryId': typeof AdminSupportInquiryIdRoute
  '/api/cart/claim': typeof ApiCartClaimRoute
  '/api/cart/merge': typeof ApiCartMergeRoute
  '/api/cart/user': typeof ApiCartUserRoute
  '/api/merchants/$merchantId': typeof ApiMerchantsMerchantIdRouteWithChildren
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/order/$orderId/confirmation': typeof OrderOrderIdConfirmationRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/api/cart/': typeof ApiCartIndexRoute
  '/api/merchants/': typeof ApiMerchantsIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/cart/$cartId/billing_address': typeof ApiCartCartIdBilling_addressRoute
  '/api/cart/$cartId/customer': typeof ApiCartCartIdCustomerRoute
  '/api/cart/$cartId/payment-intent': typeof ApiCartCartIdPaymentIntentRoute
  '/api/cart/$cartId/price': typeof ApiCartCartIdPriceRoute
  '/api/cart/$cartId/shipping': typeof ApiCartCartIdShippingRouteWithChildren
  '/api/cart/$cartId/shipping_address': typeof ApiCartCartIdShipping_addressRoute
  '/api/cart/$cartId/submit': typeof ApiCartCartIdSubmitRoute
  '/api/cart/offers/$offerId': typeof ApiCartOffersOfferIdRoute
  '/api/collections/$collectionId/products': typeof ApiCollectionsCollectionIdProductsRoute
  '/api/merchants/$merchantId/products': typeof ApiMerchantsMerchantIdProductsRoute
  '/api/cart/$cartId/': typeof ApiCartCartIdIndexRoute
  '/api/cart/$cartId/orders/$orderId': typeof ApiCartCartIdOrdersOrderIdRoute
  '/api/cart/$cartId/shipping/available': typeof ApiCartCartIdShippingAvailableRoute
  '/api/cart/$cartId/skus/$skuId': typeof ApiCartCartIdSkusSkuIdRoute
  '/api/cart/$cartId/skus/': typeof ApiCartCartIdSkusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/health': typeof AdminHealthRoute
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/guest-order-lookup': typeof ApiGuestOrderLookupRoute
  '/api/track-event': typeof ApiTrackEventRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/content/$slug': typeof ContentSlugRoute
  '/help/contact': typeof HelpContactRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/order/lookup': typeof OrderLookupRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/content': typeof ContentIndexRoute
  '/help': typeof HelpIndexRoute
  '/merchants': typeof MerchantsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/search': typeof SearchIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/support/$inquiryId': typeof AdminSupportInquiryIdRoute
  '/api/cart/claim': typeof ApiCartClaimRoute
  '/api/cart/merge': typeof ApiCartMergeRoute
  '/api/cart/user': typeof ApiCartUserRoute
  '/api/merchants/$merchantId': typeof ApiMerchantsMerchantIdRouteWithChildren
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/order/$orderId/confirmation': typeof OrderOrderIdConfirmationRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
  '/api/cart': typeof ApiCartIndexRoute
  '/api/merchants': typeof ApiMerchantsIndexRoute
  '/api/products': typeof ApiProductsIndexRoute
  '/api/cart/$cartId/billing_address': typeof ApiCartCartIdBilling_addressRoute
  '/api/cart/$cartId/customer': typeof ApiCartCartIdCustomerRoute
  '/api/cart/$cartId/payment-intent': typeof ApiCartCartIdPaymentIntentRoute
  '/api/cart/$cartId/price': typeof ApiCartCartIdPriceRoute
  '/api/cart/$cartId/shipping': typeof ApiCartCartIdShippingRouteWithChildren
  '/api/cart/$cartId/shipping_address': typeof ApiCartCartIdShipping_addressRoute
  '/api/cart/$cartId/submit': typeof ApiCartCartIdSubmitRoute
  '/api/cart/offers/$offerId': typeof ApiCartOffersOfferIdRoute
  '/api/collections/$collectionId/products': typeof ApiCollectionsCollectionIdProductsRoute
  '/api/merchants/$merchantId/products': typeof ApiMerchantsMerchantIdProductsRoute
  '/api/cart/$cartId': typeof ApiCartCartIdIndexRoute
  '/api/cart/$cartId/orders/$orderId': typeof ApiCartCartIdOrdersOrderIdRoute
  '/api/cart/$cartId/shipping/available': typeof ApiCartCartIdShippingAvailableRoute
  '/api/cart/$cartId/skus/$skuId': typeof ApiCartCartIdSkusSkuIdRoute
  '/api/cart/$cartId/skus': typeof ApiCartCartIdSkusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/health': typeof AdminHealthRoute
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/guest-order-lookup': typeof ApiGuestOrderLookupRoute
  '/api/track-event': typeof ApiTrackEventRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/content/$slug': typeof ContentSlugRoute
  '/help/contact': typeof HelpContactRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/order/lookup': typeof OrderLookupRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/content/': typeof ContentIndexRoute
  '/help/': typeof HelpIndexRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/support/$inquiryId': typeof AdminSupportInquiryIdRoute
  '/api/cart/claim': typeof ApiCartClaimRoute
  '/api/cart/merge': typeof ApiCartMergeRoute
  '/api/cart/user': typeof ApiCartUserRoute
  '/api/merchants/$merchantId': typeof ApiMerchantsMerchantIdRouteWithChildren
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/order/$orderId/confirmation': typeof OrderOrderIdConfirmationRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/api/cart/': typeof ApiCartIndexRoute
  '/api/merchants/': typeof ApiMerchantsIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/cart/$cartId/billing_address': typeof ApiCartCartIdBilling_addressRoute
  '/api/cart/$cartId/customer': typeof ApiCartCartIdCustomerRoute
  '/api/cart/$cartId/payment-intent': typeof ApiCartCartIdPaymentIntentRoute
  '/api/cart/$cartId/price': typeof ApiCartCartIdPriceRoute
  '/api/cart/$cartId/shipping': typeof ApiCartCartIdShippingRouteWithChildren
  '/api/cart/$cartId/shipping_address': typeof ApiCartCartIdShipping_addressRoute
  '/api/cart/$cartId/submit': typeof ApiCartCartIdSubmitRoute
  '/api/cart/offers/$offerId': typeof ApiCartOffersOfferIdRoute
  '/api/collections/$collectionId/products': typeof ApiCollectionsCollectionIdProductsRoute
  '/api/merchants/$merchantId/products': typeof ApiMerchantsMerchantIdProductsRoute
  '/api/cart/$cartId/': typeof ApiCartCartIdIndexRoute
  '/api/cart/$cartId/orders/$orderId': typeof ApiCartCartIdOrdersOrderIdRoute
  '/api/cart/$cartId/shipping/available': typeof ApiCartCartIdShippingAvailableRoute
  '/api/cart/$cartId/skus/$skuId': typeof ApiCartCartIdSkusSkuIdRoute
  '/api/cart/$cartId/skus/': typeof ApiCartCartIdSkusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/about'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/health'
    | '/api/exchange-rates'
    | '/api/guest-order-lookup'
    | '/api/track-event'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/collections/$collectionId'
    | '/content/$slug'
    | '/help/contact'
    | '/legal/$slug'
    | '/merchants/$merchantId'
    | '/order/lookup'
    | '/products/$productId'
    | '/admin/'
    | '/cart/'
    | '/checkout/'
    | '/collections/'
    | '/content/'
    | '/help/'
    | '/merchants/'
    | '/products/'
    | '/search/'
    | '/account/orders/$orderId'
    | '/admin/support/$inquiryId'
    | '/api/cart/claim'
    | '/api/cart/merge'
    | '/api/cart/user'
    | '/api/merchants/$merchantId'
    | '/api/orders/$orderId'
    | '/api/products/$productId'
    | '/order/$orderId/confirmation'
    | '/account/orders/'
    | '/admin/support/'
    | '/api/cart/'
    | '/api/merchants/'
    | '/api/products/'
    | '/api/cart/$cartId/billing_address'
    | '/api/cart/$cartId/customer'
    | '/api/cart/$cartId/payment-intent'
    | '/api/cart/$cartId/price'
    | '/api/cart/$cartId/shipping'
    | '/api/cart/$cartId/shipping_address'
    | '/api/cart/$cartId/submit'
    | '/api/cart/offers/$offerId'
    | '/api/collections/$collectionId/products'
    | '/api/merchants/$merchantId/products'
    | '/api/cart/$cartId/'
    | '/api/cart/$cartId/orders/$orderId'
    | '/api/cart/$cartId/shipping/available'
    | '/api/cart/$cartId/skus/$skuId'
    | '/api/cart/$cartId/skus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/about'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/health'
    | '/api/exchange-rates'
    | '/api/guest-order-lookup'
    | '/api/track-event'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/collections/$collectionId'
    | '/content/$slug'
    | '/help/contact'
    | '/legal/$slug'
    | '/merchants/$merchantId'
    | '/order/lookup'
    | '/products/$productId'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/content'
    | '/help'
    | '/merchants'
    | '/products'
    | '/search'
    | '/account/orders/$orderId'
    | '/admin/support/$inquiryId'
    | '/api/cart/claim'
    | '/api/cart/merge'
    | '/api/cart/user'
    | '/api/merchants/$merchantId'
    | '/api/orders/$orderId'
    | '/api/products/$productId'
    | '/order/$orderId/confirmation'
    | '/account/orders'
    | '/admin/support'
    | '/api/cart'
    | '/api/merchants'
    | '/api/products'
    | '/api/cart/$cartId/billing_address'
    | '/api/cart/$cartId/customer'
    | '/api/cart/$cartId/payment-intent'
    | '/api/cart/$cartId/price'
    | '/api/cart/$cartId/shipping'
    | '/api/cart/$cartId/shipping_address'
    | '/api/cart/$cartId/submit'
    | '/api/cart/offers/$offerId'
    | '/api/collections/$collectionId/products'
    | '/api/merchants/$merchantId/products'
    | '/api/cart/$cartId'
    | '/api/cart/$cartId/orders/$orderId'
    | '/api/cart/$cartId/shipping/available'
    | '/api/cart/$cartId/skus/$skuId'
    | '/api/cart/$cartId/skus'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/about'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/health'
    | '/api/exchange-rates'
    | '/api/guest-order-lookup'
    | '/api/track-event'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/collections/$collectionId'
    | '/content/$slug'
    | '/help/contact'
    | '/legal/$slug'
    | '/merchants/$merchantId'
    | '/order/lookup'
    | '/products/$productId'
    | '/admin/'
    | '/cart/'
    | '/checkout/'
    | '/collections/'
    | '/content/'
    | '/help/'
    | '/merchants/'
    | '/products/'
    | '/search/'
    | '/account/orders/$orderId'
    | '/admin/support/$inquiryId'
    | '/api/cart/claim'
    | '/api/cart/merge'
    | '/api/cart/user'
    | '/api/merchants/$merchantId'
    | '/api/orders/$orderId'
    | '/api/products/$productId'
    | '/order/$orderId/confirmation'
    | '/account/orders/'
    | '/admin/support/'
    | '/api/cart/'
    | '/api/merchants/'
    | '/api/products/'
    | '/api/cart/$cartId/billing_address'
    | '/api/cart/$cartId/customer'
    | '/api/cart/$cartId/payment-intent'
    | '/api/cart/$cartId/price'
    | '/api/cart/$cartId/shipping'
    | '/api/cart/$cartId/shipping_address'
    | '/api/cart/$cartId/submit'
    | '/api/cart/offers/$offerId'
    | '/api/collections/$collectionId/products'
    | '/api/merchants/$merchantId/products'
    | '/api/cart/$cartId/'
    | '/api/cart/$cartId/orders/$orderId'
    | '/api/cart/$cartId/shipping/available'
    | '/api/cart/$cartId/skus/$skuId'
    | '/api/cart/$cartId/skus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminHealthRoute: typeof AdminHealthRoute
  ApiExchangeRatesRoute: typeof ApiExchangeRatesRoute
  ApiGuestOrderLookupRoute: typeof ApiGuestOrderLookupRoute
  ApiTrackEventRoute: typeof ApiTrackEventRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  ContentSlugRoute: typeof ContentSlugRoute
  HelpContactRoute: typeof HelpContactRoute
  LegalSlugRoute: typeof LegalSlugRoute
  MerchantsMerchantIdRoute: typeof MerchantsMerchantIdRoute
  OrderLookupRoute: typeof OrderLookupRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ContentIndexRoute: typeof ContentIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  MerchantsIndexRoute: typeof MerchantsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  AdminSupportInquiryIdRoute: typeof AdminSupportInquiryIdRoute
  ApiCartClaimRoute: typeof ApiCartClaimRoute
  ApiCartMergeRoute: typeof ApiCartMergeRoute
  ApiCartUserRoute: typeof ApiCartUserRoute
  ApiMerchantsMerchantIdRoute: typeof ApiMerchantsMerchantIdRouteWithChildren
  ApiOrdersOrderIdRoute: typeof ApiOrdersOrderIdRoute
  ApiProductsProductIdRoute: typeof ApiProductsProductIdRoute
  OrderOrderIdConfirmationRoute: typeof OrderOrderIdConfirmationRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
  ApiCartIndexRoute: typeof ApiCartIndexRoute
  ApiMerchantsIndexRoute: typeof ApiMerchantsIndexRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
  ApiCartCartIdBilling_addressRoute: typeof ApiCartCartIdBilling_addressRoute
  ApiCartCartIdCustomerRoute: typeof ApiCartCartIdCustomerRoute
  ApiCartCartIdPaymentIntentRoute: typeof ApiCartCartIdPaymentIntentRoute
  ApiCartCartIdPriceRoute: typeof ApiCartCartIdPriceRoute
  ApiCartCartIdShippingRoute: typeof ApiCartCartIdShippingRouteWithChildren
  ApiCartCartIdShipping_addressRoute: typeof ApiCartCartIdShipping_addressRoute
  ApiCartCartIdSubmitRoute: typeof ApiCartCartIdSubmitRoute
  ApiCartOffersOfferIdRoute: typeof ApiCartOffersOfferIdRoute
  ApiCollectionsCollectionIdProductsRoute: typeof ApiCollectionsCollectionIdProductsRoute
  ApiCartCartIdIndexRoute: typeof ApiCartCartIdIndexRoute
  ApiCartCartIdOrdersOrderIdRoute: typeof ApiCartCartIdOrdersOrderIdRoute
  ApiCartCartIdSkusSkuIdRoute: typeof ApiCartCartIdSkusSkuIdRoute
  ApiCartCartIdSkusIndexRoute: typeof ApiCartCartIdSkusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/': {
      id: '/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof MerchantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/lookup': {
      id: '/order/lookup'
      path: '/order/lookup'
      fullPath: '/order/lookup'
      preLoaderRoute: typeof OrderLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$merchantId': {
      id: '/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof MerchantsMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/contact': {
      id: '/help/contact'
      path: '/help/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof HelpContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$slug': {
      id: '/content/$slug'
      path: '/content/$slug'
      fullPath: '/content/$slug'
      preLoaderRoute: typeof ContentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-event': {
      id: '/api/track-event'
      path: '/api/track-event'
      fullPath: '/api/track-event'
      preLoaderRoute: typeof ApiTrackEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-order-lookup': {
      id: '/api/guest-order-lookup'
      path: '/api/guest-order-lookup'
      fullPath: '/api/guest-order-lookup'
      preLoaderRoute: typeof ApiGuestOrderLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rates': {
      id: '/api/exchange-rates'
      path: '/api/exchange-rates'
      fullPath: '/api/exchange-rates'
      preLoaderRoute: typeof ApiExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchants/': {
      id: '/api/merchants/'
      path: '/api/merchants'
      fullPath: '/api/merchants/'
      preLoaderRoute: typeof ApiMerchantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/': {
      id: '/api/cart/'
      path: '/api/cart'
      fullPath: '/api/cart/'
      preLoaderRoute: typeof ApiCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/admin/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/order/$orderId/confirmation': {
      id: '/order/$orderId/confirmation'
      path: '/order/$orderId/confirmation'
      fullPath: '/order/$orderId/confirmation'
      preLoaderRoute: typeof OrderOrderIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$productId': {
      id: '/api/products/$productId'
      path: '/api/products/$productId'
      fullPath: '/api/products/$productId'
      preLoaderRoute: typeof ApiProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId': {
      id: '/api/orders/$orderId'
      path: '/api/orders/$orderId'
      fullPath: '/api/orders/$orderId'
      preLoaderRoute: typeof ApiOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchants/$merchantId': {
      id: '/api/merchants/$merchantId'
      path: '/api/merchants/$merchantId'
      fullPath: '/api/merchants/$merchantId'
      preLoaderRoute: typeof ApiMerchantsMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/user': {
      id: '/api/cart/user'
      path: '/api/cart/user'
      fullPath: '/api/cart/user'
      preLoaderRoute: typeof ApiCartUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/merge': {
      id: '/api/cart/merge'
      path: '/api/cart/merge'
      fullPath: '/api/cart/merge'
      preLoaderRoute: typeof ApiCartMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/claim': {
      id: '/api/cart/claim'
      path: '/api/cart/claim'
      fullPath: '/api/cart/claim'
      preLoaderRoute: typeof ApiCartClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/$inquiryId': {
      id: '/admin/support/$inquiryId'
      path: '/admin/support/$inquiryId'
      fullPath: '/admin/support/$inquiryId'
      preLoaderRoute: typeof AdminSupportInquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/api/cart/$cartId/': {
      id: '/api/cart/$cartId/'
      path: '/api/cart/$cartId'
      fullPath: '/api/cart/$cartId/'
      preLoaderRoute: typeof ApiCartCartIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchants/$merchantId/products': {
      id: '/api/merchants/$merchantId/products'
      path: '/products'
      fullPath: '/api/merchants/$merchantId/products'
      preLoaderRoute: typeof ApiMerchantsMerchantIdProductsRouteImport
      parentRoute: typeof ApiMerchantsMerchantIdRoute
    }
    '/api/collections/$collectionId/products': {
      id: '/api/collections/$collectionId/products'
      path: '/api/collections/$collectionId/products'
      fullPath: '/api/collections/$collectionId/products'
      preLoaderRoute: typeof ApiCollectionsCollectionIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/offers/$offerId': {
      id: '/api/cart/offers/$offerId'
      path: '/api/cart/offers/$offerId'
      fullPath: '/api/cart/offers/$offerId'
      preLoaderRoute: typeof ApiCartOffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/submit': {
      id: '/api/cart/$cartId/submit'
      path: '/api/cart/$cartId/submit'
      fullPath: '/api/cart/$cartId/submit'
      preLoaderRoute: typeof ApiCartCartIdSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/shipping_address': {
      id: '/api/cart/$cartId/shipping_address'
      path: '/api/cart/$cartId/shipping_address'
      fullPath: '/api/cart/$cartId/shipping_address'
      preLoaderRoute: typeof ApiCartCartIdShipping_addressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/shipping': {
      id: '/api/cart/$cartId/shipping'
      path: '/api/cart/$cartId/shipping'
      fullPath: '/api/cart/$cartId/shipping'
      preLoaderRoute: typeof ApiCartCartIdShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/price': {
      id: '/api/cart/$cartId/price'
      path: '/api/cart/$cartId/price'
      fullPath: '/api/cart/$cartId/price'
      preLoaderRoute: typeof ApiCartCartIdPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/payment-intent': {
      id: '/api/cart/$cartId/payment-intent'
      path: '/api/cart/$cartId/payment-intent'
      fullPath: '/api/cart/$cartId/payment-intent'
      preLoaderRoute: typeof ApiCartCartIdPaymentIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/customer': {
      id: '/api/cart/$cartId/customer'
      path: '/api/cart/$cartId/customer'
      fullPath: '/api/cart/$cartId/customer'
      preLoaderRoute: typeof ApiCartCartIdCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/billing_address': {
      id: '/api/cart/$cartId/billing_address'
      path: '/api/cart/$cartId/billing_address'
      fullPath: '/api/cart/$cartId/billing_address'
      preLoaderRoute: typeof ApiCartCartIdBilling_addressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/skus/': {
      id: '/api/cart/$cartId/skus/'
      path: '/api/cart/$cartId/skus'
      fullPath: '/api/cart/$cartId/skus/'
      preLoaderRoute: typeof ApiCartCartIdSkusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/skus/$skuId': {
      id: '/api/cart/$cartId/skus/$skuId'
      path: '/api/cart/$cartId/skus/$skuId'
      fullPath: '/api/cart/$cartId/skus/$skuId'
      preLoaderRoute: typeof ApiCartCartIdSkusSkuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/$cartId/shipping/available': {
      id: '/api/cart/$cartId/shipping/available'
      path: '/available'
      fullPath: '/api/cart/$cartId/shipping/available'
      preLoaderRoute: typeof ApiCartCartIdShippingAvailableRouteImport
      parentRoute: typeof ApiCartCartIdShippingRoute
    }
    '/api/cart/$cartId/orders/$orderId': {
      id: '/api/cart/$cartId/orders/$orderId'
      path: '/api/cart/$cartId/orders/$orderId'
      fullPath: '/api/cart/$cartId/orders/$orderId'
      preLoaderRoute: typeof ApiCartCartIdOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface ApiMerchantsMerchantIdRouteChildren {
  ApiMerchantsMerchantIdProductsRoute: typeof ApiMerchantsMerchantIdProductsRoute
}

const ApiMerchantsMerchantIdRouteChildren: ApiMerchantsMerchantIdRouteChildren =
  {
    ApiMerchantsMerchantIdProductsRoute: ApiMerchantsMerchantIdProductsRoute,
  }

const ApiMerchantsMerchantIdRouteWithChildren =
  ApiMerchantsMerchantIdRoute._addFileChildren(
    ApiMerchantsMerchantIdRouteChildren,
  )

interface ApiCartCartIdShippingRouteChildren {
  ApiCartCartIdShippingAvailableRoute: typeof ApiCartCartIdShippingAvailableRoute
}

const ApiCartCartIdShippingRouteChildren: ApiCartCartIdShippingRouteChildren = {
  ApiCartCartIdShippingAvailableRoute: ApiCartCartIdShippingAvailableRoute,
}

const ApiCartCartIdShippingRouteWithChildren =
  ApiCartCartIdShippingRoute._addFileChildren(
    ApiCartCartIdShippingRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminHealthRoute: AdminHealthRoute,
  ApiExchangeRatesRoute: ApiExchangeRatesRoute,
  ApiGuestOrderLookupRoute: ApiGuestOrderLookupRoute,
  ApiTrackEventRoute: ApiTrackEventRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  ContentSlugRoute: ContentSlugRoute,
  HelpContactRoute: HelpContactRoute,
  LegalSlugRoute: LegalSlugRoute,
  MerchantsMerchantIdRoute: MerchantsMerchantIdRoute,
  OrderLookupRoute: OrderLookupRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ContentIndexRoute: ContentIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  MerchantsIndexRoute: MerchantsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  AdminSupportInquiryIdRoute: AdminSupportInquiryIdRoute,
  ApiCartClaimRoute: ApiCartClaimRoute,
  ApiCartMergeRoute: ApiCartMergeRoute,
  ApiCartUserRoute: ApiCartUserRoute,
  ApiMerchantsMerchantIdRoute: ApiMerchantsMerchantIdRouteWithChildren,
  ApiOrdersOrderIdRoute: ApiOrdersOrderIdRoute,
  ApiProductsProductIdRoute: ApiProductsProductIdRoute,
  OrderOrderIdConfirmationRoute: OrderOrderIdConfirmationRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
  ApiCartIndexRoute: ApiCartIndexRoute,
  ApiMerchantsIndexRoute: ApiMerchantsIndexRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
  ApiCartCartIdBilling_addressRoute: ApiCartCartIdBilling_addressRoute,
  ApiCartCartIdCustomerRoute: ApiCartCartIdCustomerRoute,
  ApiCartCartIdPaymentIntentRoute: ApiCartCartIdPaymentIntentRoute,
  ApiCartCartIdPriceRoute: ApiCartCartIdPriceRoute,
  ApiCartCartIdShippingRoute: ApiCartCartIdShippingRouteWithChildren,
  ApiCartCartIdShipping_addressRoute: ApiCartCartIdShipping_addressRoute,
  ApiCartCartIdSubmitRoute: ApiCartCartIdSubmitRoute,
  ApiCartOffersOfferIdRoute: ApiCartOffersOfferIdRoute,
  ApiCollectionsCollectionIdProductsRoute:
    ApiCollectionsCollectionIdProductsRoute,
  ApiCartCartIdIndexRoute: ApiCartCartIdIndexRoute,
  ApiCartCartIdOrdersOrderIdRoute: ApiCartCartIdOrdersOrderIdRoute,
  ApiCartCartIdSkusSkuIdRoute: ApiCartCartIdSkusSkuIdRoute,
  ApiCartCartIdSkusIndexRoute: ApiCartCartIdSkusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
