/**
 * Guest Order Server Functions — TanStack Start RPC wrappers.
 *
 * @module server/guestOrders
 *
 * ## Two lookup paths
 *
 * 1. **Token-based**: The guest has a plaintext lookup token from the order
 *    confirmation page. We hash it server-side (SHA-256) and query by hash.
 *    No auth session required. The token is a 32-byte crypto-random value
 *    (base64url-encoded) generated by `generateOrderLookupToken()` during
 *    order persistence (Story 5.1).
 *
 * 2. **Email-based**: The guest verifies their email via Supabase OTP (magic link).
 *    After OTP verification, a temporary Supabase session exists. We confirm the
 *    session's email, then use service_role to query all orders for that email.
 *    The browser signs out after displaying results to clean up the session.
 *
 * ## Security model
 * - Token-based: Security relies on the token's entropy (256 bits). The token
 *   is only shown once on the confirmation page and stored as a SHA-256 hash
 *   in the database. No brute-force protection is needed at the query level
 *   because the search space is 2^256.
 * - Email-based: Security relies on Supabase OTP verification. The OTP session
 *   is cleaned up immediately after fetching results. Rate limiting is handled
 *   by Supabase Auth's built-in OTP rate limits.
 *
 * ## Data flow
 * ```
 * Token path:  Client → guestOrders.ts → guestOrderHandlers.ts
 *                → hashOrderLookupToken(token) → SHA-256 hex
 *                → Supabase service_role query by hash → Response
 *
 * Email path:  Client → Supabase OTP verify → guestOrders.ts → guestOrderHandlers.ts
 *                → getSupabaseSessionClient() to confirm email identity
 *                → Supabase service_role query by email → Response
 *                → Client signs out OTP session
 * ```
 *
 * ## Client bundle safety
 * Handler logic lives in guestOrderHandlers.ts and is loaded via dynamic import
 * INSIDE each .handler() closure. TanStack Start removes the .handler() body from
 * the client bundle, taking the dynamic import with it — so node:crypto (used by
 * hashOrderLookupToken) never appears in the browser build.
 *
 * @see {@link lookupOrderByTokenHandler} — token-based lookup implementation
 * @see {@link lookupOrdersByEmailHandler} — email-based lookup implementation
 * @see https://docs.violet.io/api-reference/orders-and-checkout/orders/get-order-by-id — Violet order detail (NOT used; we query Supabase)
 */

import { createServerFn } from "@tanstack/react-start";
import type { OrderWithBagsAndItems } from "@ecommerce/shared";

// ─── Server Functions (TanStack Start RPC wrappers) ───────────────────────────

/**
 * Server Function — looks up a single guest order by plaintext lookup token.
 * Hashes the token server-side before querying (SHA-256).
 *
 * @param data.token - The plaintext lookup token (base64url, 32 bytes) from the
 *   order confirmation page URL. Never stored in plaintext — only the SHA-256 hash
 *   exists in the database.
 * @returns {Promise<OrderWithBagsAndItems | null>} The matching order with full
 *   bag/item/refund detail, or null if the token doesn't match any order.
 * @throws {Error} For unexpected Supabase errors (not PGRST116).
 */
export const lookupOrderByTokenFn = createServerFn({ method: "GET" })
  .inputValidator((data: { token: string }) => data)
  .handler(async ({ data }): Promise<OrderWithBagsAndItems | null> => {
    const { lookupOrderByTokenHandler } = await import("./guestOrderHandlers");
    return lookupOrderByTokenHandler(data.token);
  });

/**
 * Server Function — fetches all guest orders for the OTP-verified session email.
 * Must be called immediately after Supabase OTP verification while session exists.
 *
 * @returns {Promise<OrderWithBagsAndItems[]>} All orders for the verified email,
 *   newest first. Empty array if no orders exist. Includes full bag/item/refund data.
 * @throws {Error} "Not authenticated" — when no valid OTP session exists (e.g., the
 *   session expired or was already signed out).
 *
 * @remarks
 * The caller (lookup.tsx) is responsible for signing out the OTP session after
 * receiving results. This function does NOT sign out — it only reads the email
 * from the session to perform the query.
 *
 * No pagination is implemented — all orders for the email are returned. This is
 * acceptable because guest orders are typically few (1-5 per email).
 */
export const lookupOrdersByEmailFn = createServerFn({ method: "GET" }).handler(
  async (): Promise<OrderWithBagsAndItems[]> => {
    const { lookupOrdersByEmailHandler } = await import("./guestOrderHandlers");
    return lookupOrdersByEmailHandler();
  },
);
