-- Migration: product_embeddings
-- Story 3.5: AI Conversational Search — Edge Function & Embeddings
-- Creates product_embeddings table with pgvector extension and HNSW index

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Product embeddings table for semantic search
CREATE TABLE public.product_embeddings (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id   VARCHAR     NOT NULL UNIQUE,
  product_name TEXT        NOT NULL,
  text_content TEXT        NOT NULL,
  embedding    vector(1536),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- HNSW index for fast cosine similarity search
CREATE INDEX idx_product_embeddings_hnsw
  ON public.product_embeddings
  USING hnsw (embedding vector_cosine_ops);

-- Auto-update updated_at on row change (reuses existing handle_updated_at function)
CREATE TRIGGER product_embeddings_updated_at
  BEFORE UPDATE ON public.product_embeddings
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- Enable Row-Level Security
ALTER TABLE public.product_embeddings ENABLE ROW LEVEL SECURITY;

-- Read access for all (anon + authenticated) — product embeddings are public data
CREATE POLICY "product_embeddings_read_all" ON public.product_embeddings
  FOR SELECT
  USING (true);

-- Write access restricted to service_role only (Edge Functions with service key)
-- No INSERT/UPDATE/DELETE policy for anon/authenticated = implicit deny

-- RPC function for cosine similarity search
CREATE OR REPLACE FUNCTION public.match_products(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.3,
  match_count int DEFAULT 12
)
RETURNS TABLE (
  product_id VARCHAR,
  product_name TEXT,
  text_content TEXT,
  similarity float
)
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    pe.product_id,
    pe.product_name,
    pe.text_content,
    1 - (pe.embedding <=> query_embedding) AS similarity
  FROM public.product_embeddings pe
  WHERE 1 - (pe.embedding <=> query_embedding) > match_threshold
  ORDER BY pe.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON TABLE public.product_embeddings IS
  'Product text embeddings for AI semantic search. Generated by OpenAI text-embedding-3-small (1536 dims).';
COMMENT ON FUNCTION public.match_products IS
  'Returns products ordered by cosine similarity to a query embedding vector.';
